# 使用 Python 官方镜像作为基础镜像
FROM python:3.10.13-slim-bullseye

RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

RUN mkdir -p /app && chown nobody:nogroup /app

WORKDIR /app
COPY . /app

RUN mkdir -p /app/shared && chown nobody:nogroup /app/shared

RUN pip install poetry -i https://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
RUN poetry config virtualenvs.create false
RUN poetry lock --no-update
RUN poetry install

RUN chmod -R 777 /app/shared

USER nobody

CMD ["bash"]
