# 使用 Python 官方镜像作为基础镜像
FROM python:3.10.13-slim-bullseye

# 设置环境变量
ENV DEBIAN_FRONTEND=noninteractive

# 设置源和时区
RUN set -eux; \
    sed -i 's/mirrors.ustc.edu.cn/deb.debian.org/g' /etc/apt/sources.list && \
    sed -i 's/mirrors.ustc.edu.cn/security.debian.org/g' /etc/apt/sources.list && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo 'Asia/Shanghai' > /etc/timezone

RUN apt-get update

# 安装 build-essential
RUN apt-get install -y build-essential

# 安装 make
RUN apt-get install -y make

# 安装 gcc
RUN apt-get install -y gcc

# 安装 g++
RUN apt-get install -y g++

# 安装 pkg-config
RUN apt-get install -y pkg-config

# 安装 tzdata
RUN apt-get install -y tzdata

# 安装 libgl1-mesa-glx
RUN apt-get install -y libgl1-mesa-glx

# 安装 libglib2.0-0
RUN apt-get install -y libglib2.0-0

# 安装 tesseract-ocr
RUN apt-get install -y tesseract-ocr

# 安装 tesseract-ocr-chi-sim
RUN apt-get install -y tesseract-ocr-chi-sim

# 清理缓存
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# 设置 pip 镜像并安装 Python 依赖
RUN pip config set global.index-url https://mirrors.ustc.edu.cn/pypi/web/simple && \
    pip install -U pip setuptools wheel && \
    pip install -U mplfonts poetry==1.8.0 && \
    mplfonts init

# 创建应用目录并设置权限
RUN mkdir -p /app /app/shared && \
    chown -R nobody:nogroup /app && \
    chmod -R 777 /app /app/shared && \
    chmod 755 /bin/bash

WORKDIR /app
COPY . /app

# 安装项目依赖
RUN poetry config virtualenvs.create false && \
    poetry lock --no-update && \
    poetry install

CMD ["bash"]
