# 运行 `export NEKRO_DATA_DIR=${HOME}/srv/nekro_agent` 设定数据目录
# 然后运行 `sudo -E docker-compose up -d` 启动服务

version: "3"

services:
  # PostgreSQL 服务
  nekro_postgres:
    image: postgres:14
    container_name: ${INSTANCE_NAME:-}nekro_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - nekro_postgres_data:/var/lib/postgresql/data
    networks:
      - nekro_network
    restart: unless-stopped

  # Qdrant 服务
  nekro_qdrant:
    image: qdrant/qdrant
    container_name: ${INSTANCE_NAME:-}nekro_qdrant
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY:-}
    volumes:
      - nekro_qdrant_data:/qdrant/storage:z
    networks:
      - nekro_network
    restart: unless-stopped

  # 主服务
  nekro_agent:
    image: kromiose/nekro-agent:latest
    container_name: ${INSTANCE_NAME:-}nekro_agent
    environment:
      - NEKRO_INSTANCE_NAME=${INSTANCE_NAME:-}nekro_agent
      - NEKRO_DATA_DIR=${NEKRO_DATA_DIR}
      - NEKRO_EXPOSE_PORT=${NEKRO_EXPOSE_PORT:-8021}
      - NEKRO_POSTGRES_HOST=${POSTGRES_HOST:-nekro_postgres}
      - NEKRO_POSTGRES_PORT=5432
      - NEKRO_POSTGRES_USER=${POSTGRES_USER:-nekro_agent}
      - NEKRO_POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-nekro_agent}
      - NEKRO_POSTGRES_DATABASE=${POSTGRES_DATABASE:-nekro_agent}
      - NEKRO_RUN_IN_DOCKER=true
      - NEKRO_ADMIN_PASSWORD=${NEKRO_ADMIN_PASSWORD:-}
      - ONEBOT_ACCESS_TOKEN=${ONEBOT_ACCESS_TOKEN:-}
      - NEKRO_QDRANT_URL=${QDRANT_URL:-http://nekro_qdrant:6333}
      - NEKRO_QDRANT_API_KEY=${QDRANT_API_KEY:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${NEKRO_DATA_DIR}:${NEKRO_DATA_DIR}:rw
    depends_on:
      - nekro_postgres
      - nekro_qdrant
    ports:
      - "${NEKRO_EXPOSE_PORT:-8021}:8021"
    networks:
      - nekro_network
    restart: unless-stopped

  # Napcat 服务
  nekro_napcat:
    image: mlikiowa/napcat-docker
    container_name: ${INSTANCE_NAME:-}nekro_napcat
    ports:
      - "${NAPCAT_EXPOSE_PORT:-6099}:6099"
    volumes:
      - ${NEKRO_DATA_DIR}:/app/nekro_agent_data
      - ${NEKRO_DATA_DIR}/napcat_data/QQ:/app/.config/QQ
      - ${NEKRO_DATA_DIR}/napcat_data/napcat:/app/napcat/config
    networks:
      - nekro_network
    restart: unless-stopped

volumes:
  nekro_postgres_data:
    name: ${INSTANCE_NAME:-}nekro_postgres_data
  nekro_qdrant_data:
    name: ${INSTANCE_NAME}nekro_qdrant_data

networks:
  nekro_network:
    name: ${INSTANCE_NAME:-}nekro_network
    driver: bridge
